### PR TITLE
Pandora (and other GLES2 platform) improved support

### PR DESCRIPTION
**Pull request by ptitSeb**
Using FBO instead of readpixel where possible.

Avoid use of "checkcolor" function, only using boundingbox test, to have good performances on GLES2 hardware (but the hotspot selection is clearly less precise).

### CODE REVIEW

**Comment by tobihan** [comment]
Hi pitSeb,

thanks for this nice pull request! Just to clarify: The --enable-pandora flag enables gles2, links to libiconv and enables fullscreen by default, right?

And the --enable-rpi and --enable-odroid flags just enable gles2? If that's the case, these two are not really needed, right?

Best,
Tobias

**Comment by ptitSeb** [comment]
For the RPi, there is some specific code in eglport for the creation context.
ODroid has nothing special for now, I just created it in case...

**Comment by tobihan** [comment]
Ok, thanks. The only small thing I noticed is that when I build the
engine with GLES2 now on Debian with GNOME 3, and I toggle between
fullscreen and windowed with Alt+Enter, the engine crashes now. Before
it didn't crash but the graphics became corrupted (only with GLES2)?
Does Alt+Enter work properly on Pandora and rpi? Maybe you want to look
into that. Anyway, I'll accept the pull request. Thanks!

**Comment by ptitSeb** [comment]
On the Pandora, fullscreen is forced, so no issue... But I'll test the Alt-Enter corruption to see if I can find a workaround (I think safest way would be to Close and Reopen GLES2 context, but that means all textures and shaders will have to be compiled again probably).

**Pull request merged**
